version: '3.9'

services:
  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge
    ports:
      - 5432:5432

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD  : example
    ports:
      - 27017:27017

  adminer:
    image: adminer
    ports:
      - 9090:8080
    depends_on:
      - postgres
