###
GET http://localhost:3000/users

###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Lucas Augusto",
    "email": "lucas.augusto5061@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "admin": true
}

###
GET http://localhost:3000/users/1 HTTP/1.1

###
GET http://localhost:3000/categories HTTP/1.1

###
GET http://localhost:3000/categories/1 HTTP/1.1

###
POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
  "name": "Sass",
  "parentId": 2
}

###
PUT http://localhost:3000/categories/4 HTTP/1.1
Content-Type: application/json

{
  "name": "React",
  "parentId": null
}

###
DELETE http://localhost:3000/categories/4 HTTP/1.1